[package]
name = "primus_fft"
version = "0.1.0"
edition = "2024"

[dependencies]
primus_integer = { path = "../primus_integer" }
num-complex = { workspace = true }
rustfft = { workspace = true }
thiserror = { workspace = true }
tfhe-fft = "0.10.1"
dyn-stack = "0.13.2"

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "fft"
harness = false

[features]
default = []
