[package]
name = "primus_glwe"
version = "0.1.0"
edition = "2024"

[dependencies]
primus_data = { path = "../primus_data" }
primus_decompose = { path = "../primus_decompose" }
primus_distr = { path = "../primus_distr" }
primus_factor = { path = "../primus_factor" }
primus_fft = { path = "../primus_fft" }
primus_encoding = { path = "../primus_encoding" }
primus_integer = { path = "../primus_integer" }
primus_lattice = { path = "../primus_lattice" }
primus_modulus = { path = "../primus_modulus" }
primus_ntt = { path = "../primus_ntt" }
primus_poly = { path = "../primus_poly" }
primus_reduce = { path = "../primus_reduce" }

num-traits = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "encryption"
harness = false

[[bench]]
name = "primitives"
harness = false

[features]
default = []
simd = [
    "primus_encoding/simd",
    "primus_factor/simd",
    "primus_integer/simd",
    "primus_modulus/simd",
    "primus_poly/simd",
    "primus_ntt/simd",
    "primus_decompose/simd",
    "primus_lattice/simd",
]
