[workspace]
members = ["crates/*", "xtask"]
resolver = "3"

[workspace.dependencies]
dashu-float = "=0.6.0"
dashu-int = "=0.6.0"
num-complex = "0.4"
num-traits = "0.2"
rand = "0.10.2"
rustfft = "6"
serde = { version = "1.0", features = ["derive"] }
zeroize = "1.9"
bytemuck = "1.25.0"
clap = { version = "4.6", features = ["derive"] }
pastey = "0.2.3"
thiserror = "2"
itertools = "0.15.0"
rayon = "1.12"

criterion = "0.8"
comfy-table = "8.0"
