[package]
name = "primus_lwe"
version = "0.1.0"
edition = "2024"

[dependencies]
primus_data = { path = "../primus_data" }
primus_decompose = { path = "../primus_decompose" }
primus_distr = { path = "../primus_distr" }
primus_encoding = { path = "../primus_encoding" }
primus_integer = { path = "../primus_integer" }
primus_lattice = { path = "../primus_lattice" }
primus_reduce = { path = "../primus_reduce" }

num-traits = { workspace = true }
rand = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
primus_modulus = { path = "../primus_modulus" }
criterion = { workspace = true }

[[bench]]
name = "lwe_enc"
harness = false

[[bench]]
name = "key_switch"
harness = false

[[bench]]
name = "public_key"
harness = false

[[bench]]
name = "batch"
harness = false

[features]
default = []
simd = [
    "primus_encoding/simd",
    "primus_integer/simd",
    "primus_lattice/simd",
    "primus_modulus/simd",
]
