[package]
name = "primus_lattice"
version = "0.1.0"
edition = "2024"

[dependencies]
primus_data = { path = "../primus_data" }
primus_integer = { path = "../primus_integer" }
primus_reduce = { path = "../primus_reduce" }
primus_modulus = { path = "../primus_modulus" }
primus_factor = { path = "../primus_factor" }
primus_distr = { path = "../primus_distr" }
primus_poly = { path = "../primus_poly" }
primus_ntt = { path = "../primus_ntt" }
primus_rns = { path = "../primus_rns", optional = true }
primus_decompose = { path = "../primus_decompose" }
primus_fft = { path = "../primus_fft" }

serde = { workspace = true }
bytemuck = { workspace = true }
rand = { workspace = true }
pastey = { workspace = true }
itertools = { workspace = true }
num-complex = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }

[[bench]]
name = "glwe_fourier"
harness = false

[[bench]]
name = "glwe_ntt"
harness = false

[[bench]]
name = "ntru_fourier"
harness = false

[[bench]]
name = "ntru_ntt"
harness = false

[[bench]]
name = "extraction"
harness = false

[[bench]]
name = "rns_glev"
harness = false
required-features = ["rns"]

[[bench]]
name = "rns_ggsw"
harness = false
required-features = ["rns"]

[features]
default = []
rns = ["dep:primus_rns"]
simd = [
    "primus_integer/simd",
    "primus_factor/simd",
    "primus_poly/simd",
    "primus_ntt/simd",
    "primus_rns?/simd",
    "primus_decompose/simd",
]
