[package]
name = "primus_distr"
version = "0.1.0"
edition = "2024"

[dependencies]
primus_integer = { path = "../primus_integer" }

thiserror = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
dashu-float = { workspace = true, optional = true }
dashu-int = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true }
comfy-table = { workspace = true }

[features]
high_precision = ["dep:dashu-float", "dep:dashu-int"]

[[bench]]
name = "sample_gaussian"
harness = false

[[bench]]
name = "gen_sampler"
harness = false

[[bench]]
name = "sample_secret_key"
harness = false
